name: Testing

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

  test-nodejs:
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Node version
        run: node --version

      - name: npm version
        run: npm --version

      - name: Yarn version
        run: yarn --version

      - name: Yarn install dependencies
        run: yarn install --frozen-lockfile

      - name: Build files
        run: yarn concat

      - name: Tree files
        run: npx tree-cli -l 5 --ignore "node_modules/, .git/"

      - name: Yarn test
        run: yarn test